### ISSUE TITLE
Work with bitlbee?

### ISSUE THREAD

**Issue by hhirtz** [matrix-org/matrix-ircd#85]
**Is your feature request related to a problem? Please describe.**
This is more of a long-term project/idea to improve maintainability and the IRC ecosystem. Feel free to close this issue or keep it in the back of your head.

**Describe the solution you'd like**
The idea behind matrix-ircd is a subset of what [bitlbee] already implements, except bitlbee doesn't implement the matrix protocol yet.

bitlbee works with plugins that implements diverse messaging protocols while being controllable through a IRC gateway. Right now it supports a [non-negligible number of protocols](https://wiki.bitlbee.org/), but not matrix.  Maybe the code in this project can be split in a library, so that a bitlbee plugin for matrix can emerge more easily.

[bitlbee]: https://github.com/bitlbee/bitlbee

**Describe alternatives you've considered**
Implement the matrix protocol by hand in a bitlbee plugin.

**Additional context**
Website: https://www.bitlbee.org/
Repo: https://github.com/bitlbee/bitlbee

**Comment by jplatte** [comment]
There's already a number of libraries around Matrix protocol usage, in particular [Ruma](https://github.com/ruma/ruma) (which I maintain together with a few other ppl) and [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk) (maintained by an Element employee and building on the lower-level Ruma crates).

If this codebase was actually in a maintainable state I would probably have rewritten it to use Ruma for many things, but sadly it is not. There is nothing to be extracted out of it.

**Comment by madduck** [comment]
@hhirtz I've been toying with that idea for months, and I even have leads that could provide a small amount of funding towards such development. If you know people who would be interested in putting forth a proposal to work on Bitlbee+Matrix, please put them in touch with me. madduck@madduck.net . Note that e2ee would be a required feature.

@jplatte You've had a good go, thank you! Made me feel better because when I tried a couple of years back, I just concluded I was too stupid, so thanks for confirming that it's just me :). If nothing else, then matrix-ircd has given us all the vision that something like this must be possible, and this vision won't die. I would take Irssi over Element any day!

**Comment by poljar** [comment]
If people aren't aware, there is a toy project that uses the matrix-rust-sdk/ruma to implement an IRC bridge, perhaps that may be an interesting starting point for a new bridge: https://github.com/martinetd/matrirc.
